version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/London
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /v2
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/London
    open-pull-requests-limit: 5
    groups:
      rust-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: cargo
    directory: /v1
    schedule:
      interval: monthly
      time: "07:00"
      timezone: Europe/London
    open-pull-requests-limit: 3
    groups:
      rust-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
